services:

  mongodb:
    image: mongo:8
    container_name: littihub-mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - mongodb_data:/data/db
    networks:
      - littihub-network


  redis:
    image: redis:7-alpine
    container_name: littihub-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: >
      redis-server
      --appendonly yes
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - littihub-network


  auth-service:
    build:
      context: ./services/auth-service
    container_name: littihub-auth-service
    restart: unless-stopped
    ports:
      - "8001:8000"
    env_file:
      - ./services/auth-service/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - littihub-network


  user-service:
    build:
      context: ./services/user-service
    container_name: littihub-user-service
    restart: unless-stopped
    ports:
      - "8002:8000"
    env_file:
      - ./services/user-service/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - littihub-network


  restaurant-service:
    build:
      context: ./services/restaurant-service
    container_name: littihub-restaurant-service
    restart: unless-stopped
    ports:
      - "8003:8000"
    env_file:
      - ./services/restaurant-service/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - littihub-network


  menu-service:
    build:
      context: ./services/menu-service
    container_name: littihub-menu-service
    restart: unless-stopped
    ports:
      - "8004:8000"
    env_file:
      - ./services/menu-service/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - littihub-network
  
  order-service:
    build:
      context: ./services/order-service
    container_name: littihub-order-service
    restart: unless-stopped
    ports:
    - "8005:8000"
    env_file:
    - ./services/order-service/.env
    depends_on:
      - mongodb
      - redis
      - user-service
      - restaurant-service
      - menu-service
    networks:
      - littihub-network

networks:
  littihub-network:
    driver: bridge


volumes:
  mongodb_data:
  redis_data:


 
